const quotes = [
    {content: "Clear alcohols are for rich women on diets."},
    {content: "Crying: acceptable at funerals and the Grand Canyon."},
    {content: "I call this turf ‘n’ turf. It's a 16 oz T-bone and a 24 oz porterhouse. Also, whiskey and a cigar. I am going to consume all of this at the same time because I am a free American."},
    {content: "Under my tutelage, you will grow from boys to men. From men into gladiators. And from gladiators into Swansons."},
    {content: "I'm a simple man. I like pretty, dark-haired women, and breakfast food."},
    {content: "Never half-ass two things. Whole-ass one thing."},
    {content: "[On bowling] Straight down the middle. No hook, no spin, no fuss. Anything more and this becomes figure skating."},
    {content: "I don't want to paint with a broad brush here, but every single contractor in the world is a miserable, incompetent thief."},
    {content: "Fishing relaxes me. It's like yoga, except I still get to kill something."},
    {content: "No home is complete without a proper toolbox. Here's April and Andy's: A hammer, a half eaten pretzel, a baseball card, some cartridge that says Sonic and Hedgehog, a scissor half, a flashlight filled with jellybeans."},
    {content: "Just give me all the bacon and eggs you have. Wait...wait. I worry what you just heard was: Give me a lot of bacon and eggs. What I said was: Give me all the bacon and eggs you have. Do you understand?"},
    {content: "When people get a little too chummy with me I like to call them by the wrong name to let them know I don't really care about them."},
    {content: "There's only one thing I hate more than lying: skim milk. Which is water that's lying about being milk."},
    {content: "The government is a greedy piglet that suckles on a taxpayer's teat until they have sore, chapped nipples."},
    {content: "The less I know about other people's affairs, the happier I am. I'm not interested in caring about people. I once worked with a guy for three years and never learned his name. Best friend I ever had. We still never talk sometimes."},
    {content: "When I eat, it is the food that is scared."},
    {content: "My only official recommendations are US Army-issued mustache trimmers, Morton's Salt, and the C.R. Lawrence Fein two inch axe-style scraper oscillating knife blade."},
    {content: "Are you going to tell a man that he can't fart in his own car?"},
    {content: "Turkey can never beat cow."},
    {content: "It's always a good idea to demonstrate to your coworkers that you are capable of withstanding a tremendous amount of pain."},
    {content: "There are three acceptable haircuts: high and tight, crew cut, buzz cut."},
    {content: "Capitalism: God's way of determining who is smart and who is poor."},
    {content: "Any dog under fifty pounds is a cat and cats are useless."},
    {content: "Fish, for sport only, not for meat. Fish meat is practically a vegetable."},
    {content: "There is only one bad word: taxes."},
    {content: "History began July 4th, 1776. Anything before that was a mistake."},
    {content: "Cultivating a manly musk puts opponent on notice."},
    {content: "Give a man a fish and feed him for a day. Don't teach a man to fish… and feed yourself. He's a grown man. And fishing's not that hard."},
    {content: "Child labor laws are ruining this country."},
    {content: "Great job, everyone. The reception will be held in each of our individual houses, alone."},
    {content: "America: The only country that matters. If you want to experience other ‘cultures,’ use an atlas or a ham radio."},
    {content: "The key to burning an ex-wife effigy is to dip it in paraffin wax and then toss the flaming bottle of isopropyl alcohol from a safe distance. Do not stand too close when you light an ex-wife effigy."},
    {content: "There are only three ways to motivate people: money, fear, and hunger."},
    {content: "Shorts over six inches are capri pants, shorts under six inches are European."},
    {content: "Friends: one to three is sufficient."},
    {content: "Breakfast food can serve many purposes."},
    {content: "Honor: if you need it defined, you don't have it."},
    {content: "One rage every three months is permitted. Try not to hurt anyone who doesn't deserve it."},
    {content: "Strippers do nothing for me…but I will take a free breakfast buffet anytime, anyplace."},
    {content: "I like saying ‘No,’ it lowers their enthusiasm."},
    {content: "You had me at meat tornado."},
    {content: "There must be a mistake, you've accidentally given me the food that my food eats."},
    {content: "Son, there is no wrong way to consume alcohol."},
    {content: "Keep your tears in your eyes where they belong."},
    {content: "I've cried twice in my life. Once when I was seven and hit by a school bus. And then again when I heard that Li'l Sebastian has passed."},
    {content: "I hate everything."},
    {content: "I love nothing."},
    {content: "I love riddles!"},
    {content: "Don't waste energy moving unless necessary."},
    {content: "I'll take that steak to go. Please and thank you."},
    {content: "Creativity is for people with glasses who like to lie."},
    {content: "Children are terrible artists and artists are crooks."},
    {content: "Tom put all my records into this rectangle!"},
    {content: "I believe luck is a concept invented by the weak to explain their failures."},
    {content: "What's cholesterol?"},
    {content: "People who buy things are suckers."},
    {content: "I'm going to get 12 eggs and part of a dead animal. Dealer's choice. Please and thank you."},
    {content: "I wanna punch you in the face so bad right now."}
];

module.exports = {quotes};